const products = [
  {
    id: 1,
    name: "Gaming Laptop",
    price: 1299,
    image: "/images/gaming-laptop.jpg",
    discount: 10,
    inventory: 25,
    description: "High-performance laptop for gaming and multitasking.",
    category: "Electronics",
    sku: "PROD-001",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Smartphone Pro",
    price: 699,
    image: "/images/smartphone-pro.jpg",
    discount: 5,
    inventory: 50,
    description: "Sleek smartphone with advanced camera and 5G.",
    category: "Electronics",
    sku: "PROD-002",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Wireless Headphones",
    price: 199,
    image: "/images/wireless-headphones.jpg",
    discount: 0,
    inventory: 100,
    description: "Noise-canceling headphones with long battery life.",
    category: "Accessories",
    sku: "PROD-003",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Smart Watch",
    price: 249,
    image: "/images/smart-watch.jpg",
    discount: 15,
    inventory: 40,
    description: "Fitness tracker with heart rate monitor and GPS.",
    category: "Accessories",
    sku: "PROD-004",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Tablet Ultra",
    price: 499,
    image: "/images/tablet-ultra.jpg",
    discount: 0,
    inventory: 30,
    description: "Lightweight tablet for work and entertainment.",
    category: "Electronics",
    sku: "PROD-005",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Portable Charger",
    price: 59,
    image: "/images/portable-charger.jpg",
    discount: 20,
    inventory: 200,
    description: "Compact charger with fast-charging capabilities.",
    category: "Accessories",
    sku: "PROD-006",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Bluetooth Speaker",
    price: 149,
    image: "/images/bluetooth-speaker.jpg",
    discount: 0,
    inventory: 75,
    description: "Portable speaker with rich sound quality.",
    category: "Accessories",
    sku: "PROD-007",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: "4K Monitor",
    price: 399,
    image: "/images/4k-monitor.jpg",
    discount: 8,
    inventory: 20,
    description: "Ultra HD monitor for crisp visuals.",
    category: "Electronics",
    sku: "PROD-008",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    name: "Mechanical Keyboard",
    price: 129,
    image: "/images/mechanical-keyboard.jpg",
    discount: 0,
    inventory: 60,
    description: "Responsive keyboard with customizable keys.",
    category: "Accessories",
    sku: "PROD-009",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 10,
    name: "Gaming Mouse",
    price: 79,
    image: "/images/gaming-mouse.jpg",
    discount: 5,
    inventory: 80,
    description: "Ergonomic mouse with programmable buttons.",
    category: "Accessories",
    sku: "PROD-010",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export default products;